### ISSUE TITLE
Identify non-doi citations

### ISSUE THREAD

**Issue by withanage** [GaziYucel/optimetaCitations#59]
@GaziYucel 

In the current  [example](https://github.com/TIBHannover/optimetaCitations/blob/main/images/optimeta-citations-submission-add.gif) , there is only for  the extraction of dois.

Are there any plans to also index non-doi content, which comes from other sources e.g. urns  ?
https://www.dnb.de/DE/Professionell/Services/URN-Service/urn-service_node.html#doc187234bodyText2

**Comment by GaziYucel** [comment]
At the moment only DOI and URL extraction is supported. URN will be added, but not planned at the moment.

**Comment by hauschke** [comment]
URN is basically only used in Germany, and even here only as an outlandish phenomenon. I would put this on a low priority. We should check, how many publications in Wikidata have a URN.

**Comment by withanage** [comment]
I agree that the global focus should not be ignored, and the urn was just meant as an example and it  can be also ignored

I think that broadly we need to look at what  kind of identifiers  are most commonly used and should support them.

My focus would try to automate as much possible to find the identifiers as much as possible for editors to decrease the manual identifier selection, which will make the plugin more usable.

I also think, Wiki data is  a good place to start  that was in the application too.

Let's may be discuss  this internally, if it should stay a focus longer-term more.
